---
title: |
  | <br><br><br><br>STOPPD cortical thickness analysis
  | (left hemisphere only)
written: 2018-03-08
edited: 2018-09-09
lastrun: Sys.Date()
output: 
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: 2
---

#This script analyses cortical thickness in the left hemisphere. 

```{r set_up, include = FALSE}

#load libraries
library(tidyverse)
library(lme4)
library(lmerTest)
library(growthmodels)


#bring in data 
df <- read_csv('../generated_csvs/STOPPD_participantsCT_20181105.csv') #generated by 05_STOPPD_error in prepartion of Jason Lerch meeting


```




```{r}
#make sure that STUDYID is an interger not a number
  df$STUDYID <- as.character(df$STUDYID)

#make sure that dateDiff is a number, not an interger
  df$dateDiff <- as.numeric(df$dateDiff)

#make a difference score 
  df$LDifference <- df$LThickness_02 - df$LThickness_01 #we're only concerned with left thickness (as per Nick's request)
  
df$RandomArm <- factor(df$randomization, 
                       levels = c("O", "P"),
                       labels = c("Olanzapine", "Placebo"))

#restructure data for RCT completers' only (N=41)
  RCT_CT <- df[(df$category == "RCT"),] 

#restructure data for RCT & Relapse participants (N=74)
  RCTRelapse_CT <- df %>%
    gather(thick_oldcolname, thickness, LThickness_01, LThickness_02) %>%
    mutate(model_days = if_else(thick_oldcolname == "LThickness_01", 1, dateDiff))

#write out clean dataframe
 # write.csv(RCT_CT, '../generated_data/df_leftCT.csv', row.names=FALSE)

```

## Print the N's



## RCT only

```{r the-ns-RCT}
RCT_CT %>% count(randomization) %>% knitr::kable() 

```


```{r RCT_CT_boxplot}
RCT_CT %>% count(randomization) %>% knitr::kable() 

#boxplot of difference in thickness (y axis) by randomization group (x axis)
  (plot <- ggplot(RCT_CT, aes(x= RandomArm, y = LDifference)) + 
     geom_boxplot(outlier.shape = NA) + 
     geom_dotplot(binaxis = 'y', stackdir = 'center') +
     geom_hline(yintercept = 0) +
     ggtitle("Cortical thickness (left hemisphere)") +
     xlab(NULL) +
     ylab("Change in Cortical Thickness (mm)")) +
  theme_minimal()
```

```{r RCT_CT_stats}
#run linear model without covariates
  fit_rct <- lm(LDifference ~ RandomArm, data= RCT_CT)
  print(fit_rct)
  summary(fit_rct)

#run linear model with covariates of sex and age
  fit_rct <- lm(LDifference ~ RandomArm + sex + age, data= RCT_CT)
  print(fit_rct)
  summary(fit_rct)

  
#run linear model with covariates of sex and age
  fit_rct <- lm(LDifference ~ RandomArm + sex + age + site, data= RCT_CT)
  print(fit_rct)
  summary(fit_rct)
```


## RCT & Relapse (with time as factor)

```{r the-ns}
RCTRelapse_CT %>% filter(model_days == 1) %>% count(randomization) %>% knitr::kable() 

```

```{r RCTRelapse_CT_plot, warning = FALSE}

#plot all data, including outlier (participant 210030)
  RCTRelapse_CT %>%
   ggplot(aes(x=model_days, y=thickness, colour=RandomArm)) + 
   geom_point() + 
   geom_line(aes(group=STUDYID), alpha = 0.5) + 
   geom_smooth(method="lm", formula=y~poly(x,1)) +
   ggtitle("Cortical thickness in left hemisphere over time") +
   labs(x = "Days between MRIs", y = "Cortical Thickness (mm)", colour = NULL) +
   theme_minimal()
```

```{r RCTRelapse_CT_stats, warning = FALSE}  
#run mixed linear model, with covariates
  fit_all <- lmer(thickness ~ RandomArm*model_days + sex + age + (1|STUDYID), data= RCTRelapse_CT)
  summary(fit_all)

```

```{r RCTRelapse_CT_statswsite, warning = FALSE}  
#run mixed linear model, with covariates
  fit_all <- lmer(thickness ~ RandomArm*model_days + sex + age + site + (1|STUDYID), data= RCTRelapse_CT)
  summary(fit_all)

```