# Surface Area Analysis

This script analyses hemisphere wide surface area 

```{r set_up, message=FALSE, warning=FALSE}

#load libraries
library(tidyverse)
library(broom)
library(lmerTest)
```

```{r message=FALSE, warning=FALSE}
#bring in data 
df <- read_csv('../generated_csvs/STOPPD_participantsCT_20181111.csv') #generated by 05_STOPPD_error in prepartion of Jason Lerch meeting

RandomArmColors = c("#e6ab02", "#386cb0")
```


```{r}
#make sure that STUDYID is an interger not a number
  df$STUDYID <- as.character(df$STUDYID)

#make sure that dateDiff is a number, not an interger
  df$dateDiff <- as.numeric(df$dateDiff)

# label the randomization variable  
df$RandomArm <- factor(df$randomization, 
                       levels = c("O", "P"),
                       labels = c("Olanzapine", "Placebo"))

#restructure data for RCT completers' only (N=40)
  RCT_SA <- df %>%
    filter(category == "RCT") 

#write out clean dataframe
 # write.csv(RCT_CT, '../generated_data/df_leftCT.csv', row.names=FALSE)

```



## RCT only


```{r RCT_SA_count}
RCT_SA %>% count(RandomArm) %>% knitr::kable() 

```

```{r RCT_LSA_stats}
fit_all <- lmer(LSurfArea_change ~ RandomArm + sex + age + (1|site), data= RCT_SA)
summary(fit_all)
```



### Right Surface Area Model

```{r RCT_RSA_stats}
fit_all <- lmer(RSurfArea_change ~ RandomArm + sex + age + (1|site), data= RCT_SA)
summary(fit_all)
```

```{r RCT_SA_facet_boxplot_fig2B, fig.height=3.5, fig.width = 5}
#boxplot of difference in thickness (y axis) by randomization group (x axis)
RCT_SA %>%
  gather(TCT, mm, LSurfArea_change, RSurfArea_change) %>%
  mutate(ThickChange = factor(TCT, levels = c("LSurfArea_change", "RSurfArea_change"),
                              labels = c("Left Hemisphere", "Right Hemisphere"))) %>%
ggplot(aes(x= RandomArm, y = mm, fill = RandomArm)) + 
     geom_boxplot(outlier.shape = NA, alpha = 0.0001) + 
     geom_dotplot(binaxis = 'y', stackdir = 'center', binwidth = 100) +
     geom_hline(yintercept = 0) +
     labs(x = NULL, y = "Change in Cortical Surface Area") +
     scale_fill_manual(values = RandomArmColors) +
     scale_shape_manual(values = c(21)) +
     facet_wrap(~ ThickChange) +
     theme_bw() +
     theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) 
     
```



## Plots and one sampled ttest in all participants

```{r}
df %>%
  gather(TCT, mm, LSurfArea_change, RSurfArea_change) %>%
  mutate(SurfAreaChange = factor(TCT, levels = c("LSurfArea_change", "RSurfArea_change"),
                              labels = c("Left Hemisphere", "Right Hemisphere")),
         Outcome = case_when(category == "Off protocol" ~ "non-completer",
                             category == "Relapse" ~ "non-completer",
                             category == "RCT"~ "completer")) %>%
  ggplot(aes(x= RandomArm, y = mm, fill = Outcome)) + 
     geom_boxplot(outlier.shape = NA) + 
     geom_dotplot(binaxis = 'y', stackdir = 'center', 
                  position=position_dodge(0.8), binwidth = 75) +
     geom_hline(yintercept = 0) +
     xlab(NULL) +
     ylab("Change in Cortical Thickness (mm)") +
     theme_bw() +
     scale_fill_manual(values = c('white','grey')) +
     facet_wrap(~SurfAreaChange)
```
```{r}
df %>%
  gather(TCT, mm, LSurfArea_change, RSurfArea_change) %>%
  mutate(SurfAreaChange = factor(TCT, levels = c("LSurfArea_change", "RSurfArea_change"),
                              labels = c("Left Hemisphere", "Right Hemisphere")),
         Outcome = case_when(category == "Off protocol" ~ "non-completer",
                             category == "Relapse" ~ "non-completer",
                             category == "RCT"~ "completer")) %>%
  group_by(SurfAreaChange, category) %>%
  do(tidy(t.test(.$mm, mu = 0, alternative = "two.sided"))) %>%
  knitr::kable()
```

## RCT & Relapse (with time as factor)


```{r the-ns-LSA}
#restructure data for RCT & Relapse participants (N=72)
  RCTRelapse_LSA <- df %>%
    gather(oldcolname, SurfArea, LSurfArea_01, LSurfArea_02) %>%
    mutate(model_days = if_else(oldcolname == "LSurfArea_01", 1, dateDiff)) %>%
mutate(category = factor(category, levels = c("RCT","Relapse", "Off protocol")),
           hemi = "Left Hemisphere")

RCTRelapse_LSA %>% filter(model_days == 1) %>% count(RandomArm) %>% knitr::kable() 

```

```{r RCTRelapse_LSA_plot_fig2DL, warning = FALSE, fig.height=4, fig.width = 4}

#plot all data, including outlier (participant 210030)
RCTRelapse_LSA %>%
  mutate(hemi = "Left Hemisphere") %>%
  ggplot(aes(x=model_days, y=SurfArea, fill = RandomArm)) + 
  geom_point(aes(shape = category)) + 
  geom_line(aes(group=STUDYID, color = RandomArm), alpha = 0.5) + 
  geom_smooth(aes(color = RandomArm), method="lm", fill = "grey40") +
  xlab("Days between MRIs") +  
  ylab(bquote('Surface Area (x1000mm'^2*')')) +
  scale_colour_manual(values = RandomArmColors) +
  scale_fill_manual(values = RandomArmColors) +
  scale_shape_manual(values = c(21:23)) +
  scale_y_continuous(limits = c(59000,115000), breaks = c(60000, 80000, 100000), labels = c('60','80','100')) +
  theme_bw()  +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  facet_wrap(~hemi)
```



```{r RCTRelapse_LSA_statswsite, warning = FALSE}  
#run mixed linear model, with covariates
  fit_all <- lmer(SurfArea ~ RandomArm*model_days + sex + age + (1|site) + (1|STUDYID), data= RCTRelapse_LSA)
  summary(fit_all)

```

### Running the right hemisphere RCTRelapse


```{r RCTRelapse_RSA_plot_fig2DR, warning = FALSE, fig.height=4, fig.width = 3.75}

#restructure data for RCT & Relapse participants (N=72)
  RCTRelapse_RSA <- df %>%
    gather(oldcolname, SurfArea, RSurfArea_01, RSurfArea_02) %>%
    mutate(model_days = if_else(oldcolname == "RSurfArea_01", 1, dateDiff)) %>%
    mutate(category = factor(category, levels = c("RCT","Relapse", "Off protocol")),
           hemi = "Right Hemisphere")
    

#plot all data, including outlier (participant 210030)
RCTRelapse_RSA %>%
  ggplot(aes(x=model_days, y=SurfArea, fill = RandomArm)) + 
  geom_point(aes(shape = category)) + 
  geom_line(aes(group=STUDYID, color = RandomArm), alpha = 0.5) + 
  geom_smooth(aes(color = RandomArm), method="lm", fill = "grey40") +
  xlab("Days between MRIs") +  
  ylab("") +
  scale_colour_manual(values = RandomArmColors) +
  scale_fill_manual(values = RandomArmColors) +
  scale_shape_manual(values = c(21:23)) +
  scale_y_continuous(limits = c(59000,115000), breaks = NULL) +
  theme_bw()  +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  facet_wrap(~hemi)

```



```{r RCTRelapse_RSA_statswsite, warning = FALSE}  
#run mixed linear model, with covariates
  fit_all <- lmer(SurfArea ~ RandomArm*model_days + sex + age + (1|site) + (1|STUDYID), data= RCTRelapse_RSA)
  summary(fit_all)

```




